import {
    BUTTON_DIRECTIVES,
    MODAL_DIRECTVES,
    DROPDOWN_DIRECTIVES,
    TAB_DIRECTIVES,
    DATEPICKER_DIRECTIVES,
    ACCORDION_DIRECTIVES,
    PROGRESSBAR_DIRECTIVES
} from 'ng2-bootstrap';

export const BS_DIRECTIVES = [
    ...BUTTON_DIRECTIVES,
    ...MODAL_DIRECTVES,
    ...DROPDOWN_DIRECTIVES,
    ...TAB_DIRECTIVES,
    ...DATEPICKER_DIRECTIVES,
    ...ACCORDION_DIRECTIVES,
    ...PROGRESSBAR_DIRECTIVES
];
