import {BUTTON_DIRECTIVES, MODAL_DIRECTVES, DROPDOWN_DIRECTIVES, TAB_DIRECTIVES, DATEPICKER_DIRECTIVES, ACCORDION_DIRECTIVES, PROGRESSBAR_DIRECTIVES} from 'ng2-bootstrap';

export const MD_COMPONENTS = [
    BUTTON_DIRECTIVES, MODAL_DIRECTVES, DROPDOWN_DIRECTIVES, TAB_DIRECTIVES, DATEPICKER_DIRECTIVES, ACCORDION_DIRECTIVES, PROGRESSBAR_DIRECTIVES
];
